### ISSUE TITLE
Function uses a lot of time

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/blade-icons#1]
Function LoadFile uses a lot of time
https://github.com/orchidsoftware/blade-icons/blob/master/src/IconFinder.php#L56

Screenshot timing http://prntscr.com/vbj994

Places where time measurment is inserted
```
    public function loadFile(string $name): ?string
    {
        start_measure('icons','Time for loadFile');
	$prefix = Str::beforeLast($name, '.');
        $name = Str::afterLast($name, '.') . '.svg';

        $icons = $this->finder
            ->ignoreUnreadableDirs()
            ->followLinks()
            ->in(
                $this->directories->get($prefix, $this->directories->toArray())
            )
            ->files()
            ->name($name);

        /** @var PathFilterIterator $iterator */
        start_measure('icons-tap','Time for tap');
        $iterator = tap($icons->getIterator())
            ->rewind();
        stop_measure('icons-tap');
        /** @var SplFileInfo|null $file */
        $file = collect($iterator)
            ->filter(static function (SplFileInfo $file) use ($name) {
                return $file->getFilename() === $name;
            })->first();
        stop_measure('icons');
        return optional($file)->getContents();
    }
```

**Desktop:**
 - Windows with VirtualBox Ubuntu:

**Server:**
  - Laravel Version: 8.12.3
  - PHP Version:  7.3.9

**Comment by PSalador** [comment]
Проблема после обновления, платформы с версии 7.x до текущей (9.x).

**Comment by PSalador** [comment]
Проблема в том что он не может найти иконки так как был префикс 'icon-'.
И получается что когда он находит иконку то запоминает её и больше не обращается - у меня после исправления префикса всего два обращения к LoadFile http://prntscr.com/vbjrau
А до исправления было 36 и каждое следующие обращение занимало больше времени http://prntscr.com/vbjs4o

**Comment by PSalador** [comment]
![image](https://user-images.githubusercontent.com/29531264/97834629-dd9f1180-1d0a-11eb-9097-9b9eba4f9142.png)

**Comment by PSalador** [comment]
Добавил 2 теста в которых измеряется добавление 200 иконок в первом тесте иконка есть, во втором нет иконок. 
В тестах видно что вторая сотня ищется в 6 раз дольше первой, что показывает гиперболическое увеличение времени поиска.

**Comment by PSalador** [comment]
Не могу закинуть из консоли - через github добавил pr #2

**Comment by tabuna** [comment]
Hi, I have optimized the code. It should be much better now. Can you check and confirm this?

**Comment by PSalador** [comment]
Yes, everything is great.
